"""Add User model and user_id for multi-tenancy

Revision ID: 7bd1ecd5815c
Revises: 7f88b0e7c0ad
Create Date: 2026-02-04 18:55:24.214928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bd1ecd5815c'
down_revision = '7f88b0e7c0ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_analysis_time'), table_name='exoplanet_candidates')
    op.drop_index(op.f('idx_source_period'), table_name='exoplanet_candidates')
    op.drop_index(op.f('idx_status'), table_name='exoplanet_candidates')
    op.drop_index(op.f('ix_exoplanet_candidates_id'), table_name='exoplanet_candidates')
    op.drop_index(op.f('ix_exoplanet_candidates_source_id'), table_name='exoplanet_candidates')
    op.drop_table('exoplanet_candidates')
    op.add_column('dataset_metadata', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_dataset_metadata_user_id'), 'dataset_metadata', ['user_id'], unique=False)
    op.add_column('ingestion_errors', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_ingestion_errors_user_id'), 'ingestion_errors', ['user_id'], unique=False)
    op.add_column('unified_star_catalog', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_unified_star_catalog_user_id'), 'unified_star_catalog', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unified_star_catalog_user_id'), table_name='unified_star_catalog')
    op.drop_column('unified_star_catalog', 'user_id')
    op.drop_index(op.f('ix_ingestion_errors_user_id'), table_name='ingestion_errors')
    op.drop_column('ingestion_errors', 'user_id')
    op.drop_index(op.f('ix_dataset_metadata_user_id'), table_name='dataset_metadata')
    op.drop_column('dataset_metadata', 'user_id')
    op.create_table('exoplanet_candidates',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('source_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('period', sa.FLOAT(), nullable=False),
    sa.Column('transit_time', sa.FLOAT(), nullable=False),
    sa.Column('duration', sa.FLOAT(), nullable=False),
    sa.Column('depth', sa.FLOAT(), nullable=False),
    sa.Column('power', sa.FLOAT(), nullable=False),
    sa.Column('snr', sa.FLOAT(), nullable=True),
    sa.Column('num_transits', sa.INTEGER(), nullable=True),
    sa.Column('visualization_json', sa.TEXT(), nullable=False),
    sa.Column('analysis_timestamp', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('mission', sa.VARCHAR(length=20), nullable=False),
    sa.Column('sector', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exoplanet_candidates_source_id'), 'exoplanet_candidates', ['source_id'], unique=False)
    op.create_index(op.f('ix_exoplanet_candidates_id'), 'exoplanet_candidates', ['id'], unique=False)
    op.create_index(op.f('idx_status'), 'exoplanet_candidates', ['status'], unique=False)
    op.create_index(op.f('idx_source_period'), 'exoplanet_candidates', ['source_id', 'period'], unique=False)
    op.create_index(op.f('idx_analysis_time'), 'exoplanet_candidates', ['analysis_timestamp'], unique=False)
    # ### end Alembic commands ###
