"""create initial schema

Revision ID: 957601232dc1
Revises: 0001_enable_postgis
Create Date: 2026-01-14 18:01:21.708053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '957601232dc1'
down_revision = '0001_enable_postgis'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset_metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('source_name', sa.String(length=500), nullable=False),
    sa.Column('catalog_type', sa.String(length=50), nullable=False),
    sa.Column('ingestion_time', sa.DateTime(), nullable=False),
    sa.Column('adapter_used', sa.String(length=100), nullable=False),
    sa.Column('schema_version', sa.String(length=20), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=True),
    sa.Column('column_mappings', sa.JSON(), nullable=True),
    sa.Column('raw_config', sa.JSON(), nullable=True),
    sa.Column('license_info', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_metadata_catalog_type'), 'dataset_metadata', ['catalog_type'], unique=False)
    op.create_index(op.f('ix_dataset_metadata_dataset_id'), 'dataset_metadata', ['dataset_id'], unique=True)
    op.create_index(op.f('ix_dataset_metadata_id'), 'dataset_metadata', ['id'], unique=False)
    op.create_table('ingestion_errors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=True),
    sa.Column('error_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('source_row', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_errors_dataset_id'), 'ingestion_errors', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_ingestion_errors_error_type'), 'ingestion_errors', ['error_type'], unique=False)
    op.create_index(op.f('ix_ingestion_errors_id'), 'ingestion_errors', ['id'], unique=False)
    op.create_index(op.f('ix_ingestion_errors_timestamp'), 'ingestion_errors', ['timestamp'], unique=False)
    op.create_table('unified_star_catalog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('object_id', sa.String(length=255), nullable=True),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('ra_deg', sa.Float(), nullable=False),
    sa.Column('dec_deg', sa.Float(), nullable=False),
    sa.Column('brightness_mag', sa.Float(), nullable=False),
    sa.Column('parallax_mas', sa.Float(), nullable=True),
    sa.Column('distance_pc', sa.Float(), nullable=True),
    sa.Column('original_source', sa.String(length=255), nullable=False),
    sa.Column('raw_frame', sa.String(length=50), nullable=False),
    sa.Column('observation_time', sa.DateTime(), nullable=True),
    sa.Column('dataset_id', sa.String(length=255), nullable=True),
    sa.Column('raw_metadata', sa.JSON(), nullable=True),
    sa.Column('fusion_group_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ra_dec_spatial', 'unified_star_catalog', ['ra_deg', 'dec_deg'], unique=False)
    op.create_index(op.f('ix_unified_star_catalog_dataset_id'), 'unified_star_catalog', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_unified_star_catalog_fusion_group_id'), 'unified_star_catalog', ['fusion_group_id'], unique=False)
    op.create_index(op.f('ix_unified_star_catalog_id'), 'unified_star_catalog', ['id'], unique=False)
    op.create_index(op.f('ix_unified_star_catalog_object_id'), 'unified_star_catalog', ['object_id'], unique=True)
    op.create_index(op.f('ix_unified_star_catalog_original_source'), 'unified_star_catalog', ['original_source'], unique=False)
    op.create_index(op.f('ix_unified_star_catalog_source_id'), 'unified_star_catalog', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unified_star_catalog_source_id'), table_name='unified_star_catalog')
    op.drop_index(op.f('ix_unified_star_catalog_original_source'), table_name='unified_star_catalog')
    op.drop_index(op.f('ix_unified_star_catalog_object_id'), table_name='unified_star_catalog')
    op.drop_index(op.f('ix_unified_star_catalog_id'), table_name='unified_star_catalog')
    op.drop_index(op.f('ix_unified_star_catalog_fusion_group_id'), table_name='unified_star_catalog')
    op.drop_index(op.f('ix_unified_star_catalog_dataset_id'), table_name='unified_star_catalog')
    op.drop_index('idx_ra_dec_spatial', table_name='unified_star_catalog')
    op.drop_table('unified_star_catalog')
    op.drop_index(op.f('ix_ingestion_errors_timestamp'), table_name='ingestion_errors')
    op.drop_index(op.f('ix_ingestion_errors_id'), table_name='ingestion_errors')
    op.drop_index(op.f('ix_ingestion_errors_error_type'), table_name='ingestion_errors')
    op.drop_index(op.f('ix_ingestion_errors_dataset_id'), table_name='ingestion_errors')
    op.drop_table('ingestion_errors')
    op.drop_index(op.f('ix_dataset_metadata_id'), table_name='dataset_metadata')
    op.drop_index(op.f('ix_dataset_metadata_dataset_id'), table_name='dataset_metadata')
    op.drop_index(op.f('ix_dataset_metadata_catalog_type'), table_name='dataset_metadata')
    op.drop_table('dataset_metadata')
    # ### end Alembic commands ###
